# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a1e00c461ee6d0417a6c975d03bbe383082478bc90adf2cb26928acd484432c5318924e8b5b7a32a49ea42b76833649b977bf5690ccd87d7e2dab22392ae0e09

test:
  secret_key_base: abec56e765d7b3cfc7c63ecb47947ba8a096da182a84ca0ab07293662f34a7a6f3aebdf99d0844b878ed1dfa7e5b624e7d2f85be036a8c6882566673856a0921

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
